FROM ubuntu:latest


COPY . ./app

RUN apt update

RUN apt install software-properties-common -y
RUN apt update
RUN add-apt-repository ppa:ondrej/php
RUN apt update
RUN apt install php7.2 -y
RUN apt install php7.2-xml -y
RUN apt install php7.2-mbstring -y
RUN apt install libapache2-mod-php7.2 -y
RUN apt install vim -y
RUN apt update
RUN cd ~
RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
RUN HASH=756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3
RUN php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer

